print(" Введите три числа")
a=int(input())
b=int(input())
c=int(input())
d=(((a+c)*b)+c)
print("Введите ваше имя")
name=input()
print("Число по заданной формуле:")
print(d)
print("Ваше имя:")
print(name)
